name: Restart Discord Bot Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:       # Permet de déclencher manuellement ce workflow

jobs:
  restart-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Utiliser la version de Python souhaitée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install discord.py

      - name: Run Discord Bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # Utilisation du secret pour le token
        run: |
          python bot.py
